import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script src="https://cdn.anychart.com/releases/8.11.1/js/anychart-core.min.js"></script>
        <script src="https://cdn.anychart.com/releases/8.11.1/js/anychart-pie.min.js"></script>
        {children}
      </body>

    </html>
  )
}
